### ISSUE TITLE
七牛的httptest.v1什么时候开源？

### ISSUE THREAD

**Issue by yangfei1028** [qiniu/httptest#1]
hello。七牛的httptest.v1什么时候开源？等的好辛苦

**Comment by sugeladi** [comment]
star 到1000吧。。

**Comment by yangfei1028** [comment]
到1000之前，可以提前尝鲜吗？

**Comment by longbai** [comment]
快了 @xushiwei 在整理

**Comment by yangfei1028** [comment]
太好啦，好消息啊

2015-07-23 22:59 GMT+08:00 Bai Long notifications@github.com:

> 快了 @xushiwei https://github.com/xushiwei 在整理
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qiniu/httptest.v1/issues/1#issuecomment-124132569.

## 

---

D.yang

研发部 果壳网

**Comment by safeoy** [comment]
期待

**Comment by Alvinzhao** [comment]
基于Python的pyparse吗?
